# Generated by Django 2.0.6 on 2019-05-19 08:32

from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TAddress',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
                ('detail_address', models.CharField(max_length=40)),
                ('zipcode', models.CharField(max_length=20)),
                ('telphone', models.CharField(blank=True, max_length=40, null=True)),
                ('addr_mobile', models.CharField(blank=True, max_length=40, null=True)),
                ('user_id', models.CharField(max_length=40)),
            ],
            options={
                'db_table': 't_address',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TBook',
            fields=[
                ('book_id', models.IntegerField(primary_key=True, serialize=False)),
                ('book_name', models.CharField(blank=True, max_length=128, null=True)),
                ('book_author', models.CharField(blank=True, max_length=64, null=True)),
                ('book_publish', models.CharField(blank=True, max_length=128, null=True)),
                ('publish_time', models.DateField(blank=True, null=True)),
                ('revision', models.IntegerField(blank=True, null=True)),
                ('book_isbn', models.CharField(blank=True, max_length=64, null=True)),
                ('word_count', models.CharField(blank=True, max_length=64, null=True)),
                ('page_count', models.IntegerField(blank=True, null=True)),
                ('book_paper', models.CharField(blank=True, max_length=64, null=True)),
                ('book_wrapper', models.CharField(blank=True, max_length=64, null=True)),
                ('book_category', models.CharField(blank=True, max_length=40, null=True)),
                ('book_price', models.FloatField(blank=True, null=True)),
                ('book_dprice', models.FloatField(blank=True, null=True)),
                ('series_name', models.CharField(blank=True, max_length=64, null=True)),
                ('printing_time', models.DateField(blank=True, null=True)),
                ('impression', models.CharField(blank=True, max_length=64, null=True)),
                ('stock', models.IntegerField(blank=True, null=True)),
                ('shelves_date', models.DateField(blank=True, null=True)),
                ('customer_socre', models.CharField(blank=True, max_length=64, null=True)),
                ('book_status', models.CharField(blank=True, max_length=64, null=True)),
                ('sales', models.CharField(blank=True, max_length=64, null=True)),
                ('book_pic', models.CharField(blank=True, max_length=300, null=True)),
            ],
            options={
                'db_table': 't_book',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TCategory',
            fields=[
                ('idcategory_id', models.IntegerField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=40)),
                ('book_counts', models.CharField(blank=True, max_length=40, null=True)),
                ('category_pid', models.CharField(blank=True, max_length=40, null=True)),
            ],
            options={
                'db_table': 't_category',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TOrder',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('num', models.CharField(blank=True, max_length=40, null=True)),
                ('create_date', models.DateTimeField(blank=True, null=True)),
                ('price', models.FloatField(blank=True, null=True)),
                ('order_addrid', models.CharField(max_length=40)),
                ('order_uid', models.CharField(max_length=40)),
                ('status', models.CharField(blank=True, max_length=40, null=True)),
            ],
            options={
                'db_table': 't_order',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TOrderitem',
            fields=[
                ('shop_id', models.IntegerField(primary_key=True, serialize=False)),
                ('shop_ordid', models.CharField(max_length=40)),
                ('shop_bookid', models.CharField(max_length=40)),
                ('shop_num', models.CharField(max_length=40)),
                ('total_price', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 't_orderitem',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TUser',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False)),
                ('user_email', models.EmailField(max_length=254, verbose_name='邮箱')),
                ('user_name', models.CharField(blank=True, max_length=40, null=True)),
                ('user_password', models.CharField(blank=True, max_length=40, null=True)),
                ('user_status', models.CharField(blank=True, max_length=40, null=True)),
                ('c_time', models.DateTimeField(auto_now_add=True)),
                ('has_confirm', models.BooleanField(default=False, verbose_name='是否确认')),
            ],
            options={
                'db_table': 't_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Confirm_string',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=256, verbose_name='用户注册码')),
                ('code_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 't_confirm_string',
            },
        ),
        migrations.AddField(
            model_name='confirm_string',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.TUser', verbose_name='关联的用户'),
        ),
    ]
