# Generated by Django 2.0.6 on 2019-05-26 03:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tuser',
            options={},
        ),
    ]
